import type { Book1EditorialPage } from '../../experiences/magazine/magazineTypes';

export const book1EditorialPages: Book1EditorialPage[] = [
  {
    number: 1,
    id: 'book1-p01-social-structure',
    kicker: '01 / KHÁI NIỆM',
    headline: 'Cơ cấu xã hội là gì?',
    body: 'Cơ cấu xã hội gồm những cộng đồng người cùng toàn bộ các mối quan hệ xã hội do sự tác động lẫn nhau giữa các cộng đồng ấy tạo nên.',
    labels: ['Cộng đồng người', 'Mối quan hệ xã hội'],
    layout: 'definition',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'equation',
      terms: ['Cộng đồng người', 'Mối quan hệ xã hội'],
      result: 'Cơ cấu xã hội',
    },
  },
  {
    number: 2,
    id: 'book1-p02-five-structures',
    kicker: '02 / CÁC LOẠI HÌNH',
    headline: 'Năm lát cắt của cơ cấu xã hội',
    body: 'Dân cư, nghề nghiệp, giai cấp, dân tộc và tôn giáo cùng tồn tại và tác động qua lại trong đời sống xã hội.',
    labels: ['Dân cư', 'Nghề nghiệp', 'Giai cấp', 'Dân tộc', 'Tôn giáo'],
    layout: 'constellation',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'constellation',
      center: 'Cơ cấu xã hội',
      nodes: [
        { id: 'dc', label: 'Dân cư' },
        { id: 'nn', label: 'Nghề nghiệp' },
        { id: 'gc', label: 'Giai cấp', highlighted: true },
        { id: 'dt', label: 'Dân tộc' },
        { id: 'tg', label: 'Tôn giáo' },
      ],
      highlightedCaption: 'Chủ nghĩa xã hội khoa học tập trung nghiên cứu cơ cấu xã hội – giai cấp do mối liên hệ trực tiếp với giai cấp, lợi ích và liên minh.',
    },
  },
  {
    number: 3,
    id: 'book1-p03-class-social-structure',
    kicker: '03 / CƠ CẤU XH–GC',
    headline: 'Một hệ thống các giai cấp và tầng lớp',
    body: 'Cơ cấu xã hội – giai cấp là hệ thống các giai cấp, tầng lớp xã hội tồn tại khách quan trong một chế độ xã hội nhất định.',
    layout: 'definition',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'class-system',
      center: 'Cơ cấu xã hội – giai cấp',
      nodes: ['Giai cấp', 'Tầng lớp xã hội'],
      caption: 'Tồn tại khách quan trong một chế độ xã hội nhất định',
    },
  },
  {
    number: 4,
    id: 'book1-p04-four-dimensions',
    kicker: '04 / BỐN CHIỀU KÍCH',
    headline: 'Nhìn cấu trúc qua bốn quan hệ',
    labels: [
      'Sở hữu tư liệu sản xuất',
      'Tổ chức và quản lý sản xuất',
      'Địa vị chính trị – xã hội',
      'Phân phối sản phẩm và thu nhập',
    ],
    footer: 'TKQĐ: công nhân · nông dân · trí thức · doanh nhân · tiểu chủ · các nhóm xã hội khác',
    layout: 'four-dimensions',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'four-dimensions',
      dimensions: [
        'Sở hữu tư liệu sản xuất',
        'Tổ chức và quản lý sản xuất',
        'Địa vị chính trị – xã hội',
        'Phân phối sản phẩm và thu nhập',
      ],
    },
  },
  {
    number: 5,
    id: 'book1-p05-position',
    kicker: '05 / VỊ TRÍ',
    headline: 'Giữ vị trí quan trọng hàng đầu',
    body: 'Cơ cấu xã hội – giai cấp gắn chặt với các quan hệ kinh tế, chính trị và có ảnh hưởng mạnh tới những loại hình cơ cấu xã hội khác.',
    layout: 'orbital',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'orbital',
      center: 'Cơ cấu XH – giai cấp',
      nodes: ['Dân cư', 'Nghề nghiệp', 'Tôn giáo', 'Dân tộc'],
      direction: 'outward',
      caption: 'Có ảnh hưởng mạnh tới các cơ cấu xã hội khác',
    },
  },
  {
    number: 6,
    id: 'book1-p06-two-way',
    kicker: '06 / TÁC ĐỘNG QUA LẠI',
    headline: 'Quan trọng, nhưng không đứng một mình',
    body: 'Dân tộc, tôn giáo, dân cư và nghề nghiệp cũng tác động trở lại. Không tuyệt đối hóa cơ cấu xã hội – giai cấp và không xem nhẹ các cơ cấu khác.',
    layout: 'orbital',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'orbital',
      center: 'Cơ cấu XH – giai cấp',
      nodes: ['Dân cư', 'Nghề nghiệp', 'Tôn giáo', 'Dân tộc'],
      direction: 'reciprocal',
      caption: 'Tác động qua lại hai chiều',
    },
  },
  {
    number: 7,
    id: 'book1-p07-trend-one',
    kicker: '07 / XU HƯỚNG 1',
    headline: 'Kinh tế thay đổi, cơ cấu giai cấp thay đổi',
    body: 'Sự biến đổi của cơ cấu xã hội – giai cấp gắn liền và bị quy định bởi sự biến đổi của cơ cấu kinh tế trong thời kỳ quá độ.',
    layout: 'flow',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'flow',
      steps: ['Kinh tế thay đổi', 'Cơ cấu kinh tế chuyển dịch', 'Cơ cấu giai cấp thay đổi'],
    },
  },
  {
    number: 8,
    id: 'book1-p08-economic-chain',
    kicker: '08 / CHUỖI CHUYỂN DỊCH',
    headline: 'Từ cơ cấu kinh tế đến diện mạo giai tầng',
    labels: [
      'Cơ cấu kinh tế',
      'Lao động & nghề nghiệp',
      'Vị trí · số lượng · vai trò',
      'Cơ cấu xã hội – giai cấp',
    ],
    footer: 'Minh họa công nghiệp hóa: tỷ trọng nông nghiệp có xu hướng giảm tương đối, công nghiệp và dịch vụ tăng.',
    layout: 'flow',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'flow',
      steps: [
        'Cơ cấu kinh tế',
        'Lao động & nghề nghiệp',
        'Vị trí · số lượng · vai trò',
        'Cơ cấu xã hội – giai cấp',
      ],
    },
  },
  {
    number: 9,
    id: 'book1-p09-trend-two',
    kicker: '09 / XU HƯỚNG 2',
    headline: 'Phức tạp hơn, đa dạng hơn',
    body: 'Nhiều thành phần kinh tế và hình thức sở hữu làm cơ cấu xã hội – giai cấp thêm đa dạng, đồng thời làm xuất hiện những tầng lớp xã hội mới.',
    layout: 'branching',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'branching',
      heading: 'Kinh tế nhiều thành phần',
      items: ['Đa dạng hóa cơ cấu giai cấp', 'Xuất hiện tầng lớp xã hội mới'],
    },
  },
  {
    number: 10,
    id: 'book1-p10-internal-differentiation',
    kicker: '10 / PHÂN HÓA',
    headline: 'Khác biệt diễn ra cả bên trong mỗi giai tầng',
    labels: ['Nghề nghiệp', 'Trình độ', 'Thu nhập', 'Điều kiện sống', 'Vị thế xã hội'],
    footer: 'Doanh nhân · tiểu chủ · lao động tự do là những ví dụ minh họa cho diện mạo xã hội đa dạng hơn.',
    layout: 'branching',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'branching',
      heading: 'Tiêu chí phân hóa nội bộ',
      items: ['Nghề nghiệp', 'Trình độ', 'Thu nhập', 'Điều kiện sống', 'Vị thế xã hội'],
    },
  },
  {
    number: 11,
    id: 'book1-p11-trend-three',
    kicker: '11 / XU HƯỚNG 3',
    headline: 'Vừa đấu tranh, vừa liên minh',
    body: 'Lợi ích giữa các giai cấp, tầng lớp vừa có điểm chung vừa có khác biệt; vì vậy quan hệ xã hội bao gồm cả hợp tác, liên minh và những căng thẳng, khác biệt.',
    layout: 'convergence',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'convergence',
      leftLabel: 'Mặt thống nhất',
      leftTitle: 'Hợp tác & Liên minh',
      rightLabel: 'Mặt khác biệt',
      rightTitle: 'Khác biệt & Đấu tranh',
      convergenceLabel: 'Quan hệ xã hội đan xen',
    },
  },
  {
    number: 12,
    id: 'book1-p12-draw-closer',
    kicker: '12 / XÍCH LẠI GẦN NHAU',
    headline: 'Thu hẹp những khoảng cách bất hợp lý',
    body: 'Trong quá trình phát triển và liên minh, các giai cấp, tầng lớp có xu hướng từng bước xích lại gần nhau; sự khác biệt không vì thế mà biến mất hoàn toàn.',
    layout: 'convergence',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'convergence',
      leftLabel: 'Phát triển kinh tế',
      leftTitle: 'Liên minh giai tầng',
      rightLabel: 'Đặc thù giai cấp',
      rightTitle: 'Khác biệt tồn tại',
      convergenceLabel: 'Từng bước xích lại gần nhau',
    },
  },
  {
    number: 13,
    id: 'book1-p13-synthesis',
    kicker: '13 / LOGIC TỔNG HỢP',
    headline: 'Ba chuyển động nối thành một chuỗi',
    labels: [
      'Kinh tế thay đổi',
      'Cơ cấu XH–GC thay đổi',
      'Lợi ích vừa thống nhất vừa khác biệt',
    ],
    layout: 'synthesis',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'synthesis',
      steps: [
        'Kinh tế thay đổi',
        'Cơ cấu XH–GC thay đổi',
        'Lợi ích vừa thống nhất vừa khác biệt',
      ],
    },
  },
  {
    number: 14,
    id: 'book1-p14-bridge',
    kicker: '14 / CÂU HỎI CHUYỂN TIẾP',
    headline: 'Khi lợi ích vừa gặp nhau vừa khác nhau…',
    body: 'Điều gì khiến các giai cấp và tầng lớp phải liên minh?',
    layout: 'transition',
    sourceIds: ['giaoTrinh2021'],
    visual: {
      kind: 'transition',
      label: 'Câu hỏi chuyển tiếp sang Quyển II',
    },
  },
];

export const BOOK1_EDITORIAL_PAGE_COUNT = book1EditorialPages.length;
