import type { PresentationScene } from './types';

export const part1Scenes: PresentationScene[] = [
  {
    id: 'p1-s0',
    chapterId: 'part-1',
    order: 0,
    kicker: 'Phần thứ nhất',
    title: 'Khái luận về cơ cấu xã hội – giai cấp',
    subtitle: 'Khái niệm · Vị trí · Sự biến đổi có tính quy luật',
    body: [
      'Trong hệ thống xã hội, cơ cấu xã hội – giai cấp giữ vị trí quan trọng hàng đầu và có ảnh hưởng mạnh tới các loại hình cơ cấu xã hội khác trong thời kỳ quá độ lên chủ nghĩa xã hội.',
    ],
    visual: {
      id: 'paper',
      variant: 'leather-folio',
    },
    beats: [
      {
        id: 'p1-s0-b0',
        label: 'Mở đầu chương',
        durationMs: 800,
      },
      {
        id: 'p1-s0-b1',
        label: 'Đặt 3 vấn đề trọng tâm',
        emphasis: ['core-questions'],
        durationMs: 700,
      },
    ],
    speakerNotes: [
      'Giới thiệu tổng quan Phần I của Chương 5: Cơ cấu xã hội - giai cấp và liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH.',
      'Nhấn mạnh 3 câu hỏi xuyên suốt: (1) Cơ cấu xã hội - giai cấp là gì? (2) Vị trí của nó thế nào trong hệ thống xã hội? (3) Quy luật biến đổi trong thời kỳ quá độ ra sao?',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I',
    transitionIn: 'book-open',
  },
  {
    id: 'p1-s1',
    chapterId: 'part-1',
    order: 1,
    kicker: '1. Khái niệm cơ bản',
    title: 'Cơ cấu xã hội là gì?',
    subtitle: 'Hệ thống các cộng đồng người cùng toàn bộ các mối quan hệ xã hội',
    body: [
      'Cơ cấu xã hội là những cộng đồng người cùng toàn bộ những mối quan hệ xã hội do sự tác động lẫn nhau của các cộng đồng ấy tạo nên.',
    ],
    labels: [
      { id: 'node-dancu', text: 'Dân cư', sub: 'Lãnh thổ / Địa bàn sinh sống' },
      { id: 'node-nghenghiep', text: 'Nghề nghiệp', sub: 'Phân công lao động xã hội' },
      { id: 'node-giaicap', text: 'Giai cấp', sub: 'Địa vị kinh tế - xã hội' },
      { id: 'node-dantoc', text: 'Dân tộc', sub: 'Quan hệ tộc người / Bản sắc' },
      { id: 'node-tongiao', text: 'Tôn giáo', sub: 'Niềm tin & Sinh hoạt tâm linh' },
    ],
    visual: {
      id: 'constellation',
      variant: 'social-network',
      props: {
        nodeCount: 5,
        interactive: true,
      },
    },
    beats: [
      {
        id: 'p1-s1-b0',
        label: 'Xuất hiện 5 cộng đồng xã hội',
        reveal: ['nodes'],
        durationMs: 600,
      },
      {
        id: 'p1-s1-b1',
        label: 'Hình thành mạng lưới liên kết',
        reveal: ['links'],
        durationMs: 800,
      },
      {
        id: 'p1-s1-b2',
        label: 'Định nghĩa cơ cấu xã hội cốt lõi',
        reveal: ['definition-card'],
        emphasis: ['definition'],
        durationMs: 700,
      },
    ],
    speakerNotes: [
      'Nhắc lại: Xã hội không phải là tập hợp rời rạc các cá nhân đơn lẻ.',
      'Beat 1: Chỉ ra 5 phân hệ cộng đồng cơ bản: dân cư, nghề nghiệp, giai cấp, dân tộc, tôn giáo.',
      'Beat 2: Nhấn mạnh sự tương tác qua lại giữa các phân hệ tạo thành mạng lưới quan hệ xã hội.',
      'Beat 3: Khắc sâu công thức: Cơ cấu xã hội = Các cộng đồng người + Các mối quan hệ xã hội giữa họ.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.1',
    transitionIn: 'fade',
  },
  {
    id: 'p1-s2',
    chapterId: 'part-1',
    order: 2,
    kicker: '2. Bản chất cấu trúc',
    title: 'Cơ cấu xã hội – giai cấp là gì?',
    subtitle: 'Hệ thống các giai cấp, tầng lớp và 4 chiều kích quan hệ sản xuất',
    body: [
      'Cơ cấu xã hội – giai cấp là hệ thống các giai cấp, tầng lớp xã hội tồn tại khách quan trong một chế độ xã hội nhất định, thông qua 4 mối quan hệ cốt lõi: sở hữu tư liệu sản xuất, tổ chức quản lý sản xuất, địa vị chính trị – xã hội, và phân phối sản phẩm lao động / thu nhập.',
    ],
    visual: {
      id: 'class-relations',
    },
    visualLabels: [
      { id: 'TLSX', text: 'Quan hệ sở hữu', sub: 'Tư liệu sản xuất', role: 'Quyết định trực tiếp địa vị giai cấp trong nền sản xuất' },
      { id: 'QUAN_LY', text: 'Tổ chức quản lý', sub: 'Lao động và sản xuất', role: 'Phân công lao động xã hội và điều hành quy trình sản xuất' },
      { id: 'DIA_VI', text: 'Địa vị chính trị - xã hội', sub: 'Trong hệ thống quan hệ', role: 'Quy định quyền lực và vai trò xã hội giữa các giai cấp' },
      { id: 'PHAN_PHOI', text: 'Phân phối thu nhập', sub: 'Sản phẩm lao động', role: 'Phương thức và quy mô hưởng thụ thành quả lao động xã hội' },
    ],
    beats: [
      { id: 'p1-s2-b0', label: 'Khảo sát hệ thống giai cấp, tầng lớp xã hội', durationMs: 700 },
      { id: 'p1-s2-b1', label: 'Phân tích 4 chiều kích quan hệ sản xuất', durationMs: 800 },
      { id: 'p1-s2-b2', label: 'Quan hệ Sở hữu TLSX & Tổ chức quản lý lao động', durationMs: 800 },
      { id: 'p1-s2-b3', label: 'Địa vị chính trị – xã hội & Phương thức phân phối thu nhập', durationMs: 800 },
      { id: 'p1-s2-b4', label: 'Định nghĩa khoa học hoàn chỉnh về cơ cấu xã hội – giai cấp', durationMs: 900 },
    ],
    speakerNotes: [
      'Phân tích theo định nghĩa giai cấp kinh điển của V.I.Lênin gắn liền với 4 chiều kích: (1) Quan hệ sở hữu TLSX; (2) Vai trò tổ chức quản lý lao động; (3) Địa vị chính trị - xã hội; (4) Phương thức và quy mô phân phối thu nhập.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.1',
  },
  {
    id: 'p1-s3',
    chapterId: 'part-1',
    order: 3,
    kicker: '3. Vị trí trung tâm & Tác động qua lại',
    title: 'Vị trí của cơ cấu xã hội – giai cấp',
    subtitle: 'Giữ vị trí quan trọng hàng đầu trong mối quan hệ biện chứng hai chiều',
    body: [
      'Cơ cấu xã hội – giai cấp giữ vị trí quan trọng hàng đầu, có ảnh hưởng mạnh tới các loại hình cơ cấu xã hội khác, đồng thời chịu sự tác động trở lại của cơ cấu dân tộc, tôn giáo, dân số và nghề nghiệp.',
      'Không được tuyệt đối hóa vai trò của cơ cấu xã hội – giai cấp và xem nhẹ các loại hình cơ cấu xã hội khác.',
    ],
    visual: {
      id: 'orbital-centrality',
    },
    visualLabels: [
      { id: 'CENTRAL', text: 'Cơ cấu XH - Giai cấp', sub: 'Vị trí trung tâm hàng đầu', role: 'Hạt nhân trung tâm, phản ánh và tác động trực tiếp đến quan hệ sản xuất' },
      { id: 'DANTOC', text: 'Cơ cấu Dân tộc', sub: 'Quan hệ tộc người', role: 'Tác động sâu sắc đến khối đại đoàn kết và ổn định chính trị' },
      { id: 'TONGIAO', text: 'Cơ cấu Tôn giáo', sub: 'Đời sống tín ngưỡng', role: 'Ảnh hưởng tới tâm lý, đạo đức và khối liên minh xã hội' },
      { id: 'DANSO', text: 'Cơ cấu Dân cư / Dân số', sub: 'Quy mô & Phân bố', role: 'Cung cấp nguồn nhân lực và nền tảng không gian sinh tồn' },
      { id: 'NGHENGHIEP', text: 'Cơ cấu Nghề nghiệp', sub: 'Phân công lao động', role: 'Tạo cơ sở kinh tế - kỹ thuật trực tiếp hình thành giai tầng' },
    ],
    beats: [
      { id: 'p1-s3-b0', label: 'Hạt nhân trung tâm quan trọng hàng đầu', durationMs: 700 },
      { id: 'p1-s3-b1', label: 'Hệ thống 4 cơ cấu xã hội vệ tinh', durationMs: 800 },
      { id: 'p1-s3-b2', label: 'Ảnh hưởng mạnh mẽ tới các cơ cấu xã hội khác', durationMs: 800 },
      { id: 'p1-s3-b3', label: 'Sự tác động trở lại của dân tộc, tôn giáo, dân số, nghề nghiệp', durationMs: 900 },
      { id: 'p1-s3-b4', label: 'Nguyên lý phương pháp luận: Không tuyệt đối hóa, không xem nhẹ', durationMs: 800 },
    ],
    speakerNotes: [
      'Nhấn mạnh nguyên lý biện chứng: Cơ cấu xã hội - giai cấp giữ vị trí trọng yếu hàng đầu nhưng tồn tại trong mối tác động qua lại với các cơ cấu khác.',
      'Cảnh báo sai lầm: Không được tuyệt đối hóa vai trò của cơ cấu xã hội – giai cấp và xem nhẹ các loại hình cơ cấu xã hội khác.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.1',
  },
  {
    id: 'p1-s4',
    chapterId: 'part-1',
    order: 4,
    kicker: '4. Sự biến đổi có tính quy luật — Xu hướng 1',
    title: 'Gắn liền và bị quy định bởi cơ cấu kinh tế',
    subtitle: 'Sự biến đổi của cơ cấu xã hội – giai cấp vận động cùng cơ cấu kinh tế',
    body: [
      'Cơ cấu xã hội – giai cấp biến đổi gắn liền và bị quy định bởi sự biến đổi của cơ cấu kinh tế trong thời kỳ quá độ lên chủ nghĩa xã hội.',
    ],
    visual: {
      id: 'structure-flow',
    },
    visualLabels: [
      { id: 'GATE_1', text: 'Cơ cấu kinh tế', sub: 'Nền tảng hạ tầng', role: 'Kinh tế nhiều thành phần định hướng XHCN vận động, chuyển dịch' },
      { id: 'GATE_2', text: 'Ngành & Sở hữu', sub: 'Phương thức sản xuất', role: 'Chuyển dịch công nghiệp hóa, hiện đại hóa và đa dạng hóa sở hữu' },
      { id: 'GATE_3', text: 'Phân công lao động', sub: 'Cơ cấu ngành nghề', role: 'Dịch chuyển lao động từ nông nghiệp sang công nghiệp và dịch vụ' },
      { id: 'GATE_4', text: 'Địa vị & Vai trò', sub: 'Các giai tầng xã hội', role: 'Vị trí kinh tế - xã hội của từng giai cấp vận động phù hợp thể chế' },
      { id: 'GATE_5', text: 'Cơ cấu XH - Giai cấp', sub: 'Kết quả biến đổi tất yếu', role: 'Diện mạo giai tầng mới được xác lập tương ứng với trình độ kinh tế' },
    ],
    beats: [
      { id: 'p1-s4-b0', label: 'Cơ cấu kinh tế nhiều thành phần chuyển dịch', durationMs: 700 },
      { id: 'p1-s4-b1', label: 'Chuyển dịch cơ cấu ngành, thành phần kinh tế và PTSX', durationMs: 800 },
      { id: 'p1-s4-b2', label: 'Phân công lao động và chuyển dịch cơ cấu việc làm', durationMs: 800 },
      { id: 'p1-s4-b3', label: 'Biến đổi vị trí, vai trò của các giai cấp, tầng lớp', durationMs: 800 },
      { id: 'p1-s4-b4', label: 'Cơ cấu xã hội – giai cấp biến đổi tương ứng', durationMs: 900 },
    ],
    speakerNotes: [
      'Xu hướng 1: Khi cơ cấu kinh tế chuyển dịch (công nghiệp hóa, hiện đại hóa, kinh tế thị trường định hướng XHCN), cơ cấu giai tầng cũng biến đổi theo.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.2',
  },
  {
    id: 'p1-s5',
    chapterId: 'part-1',
    order: 5,
    kicker: '5. Sự biến đổi có tính quy luật — Xu hướng 2',
    title: 'Biến đổi phức tạp, đa dạng và xuất hiện tầng lớp mới',
    subtitle: 'Nền kinh tế nhiều thành phần tạo nên diện mạo xã hội đa tầng',
    body: [
      'Cơ cấu xã hội – giai cấp biến đổi phức tạp, đa dạng, làm xuất hiện các tầng lớp xã hội mới như đội ngũ doanh nhân, tầng lớp tiểu chủ, người làm nghề tự do.',
    ],
    visual: {
      id: 'diversification',
    },
    visualLabels: [
      { id: 'GROUP_A', text: 'Giai cấp công nhân', sub: 'Lực lượng tiêu biểu trong công nghiệp hóa', role: 'Vận động và phát triển trong nền kinh tế nhiều thành phần' },
      { id: 'GROUP_B', text: 'Giai cấp nông dân', sub: 'Lực lượng tiêu biểu trong nông nghiệp', role: 'Chuyển dịch cơ cấu lao động và đa dạng hóa ngành nghề' },
      { id: 'GROUP_C', text: 'Đội ngũ trí thức', sub: 'Lao động sáng tạo trí tuệ', role: 'Gia tăng vai trò cùng sự phát triển khoa học công nghệ' },
      { id: 'GROUP_D', text: 'Đội ngũ doanh nhân', sub: 'Tầng lớp xã hội mới tiêu biểu', role: 'Minh họa sự xuất hiện của tầng lớp mới trong kinh tế thị trường' },
      { id: 'GROUP_E', text: 'Tầng lớp tiểu chủ & tự do', sub: 'Khu vực kinh tế cá thể, dịch vụ', role: 'Minh họa tính đa dạng, linh hoạt của phân công lao động mới' },
    ],
    beats: [
      { id: 'p1-s5-b0', label: 'Các giai tầng tiêu biểu ban đầu trong mô hình minh họa', durationMs: 700, speakerNote: 'Bắt đầu từ các giai tầng tiêu biểu ban đầu trong mô hình xã hội công nghiệp hóa.' },
      { id: 'p1-s5-b1', label: 'Sự phân hóa nội bộ bắt đầu diễn ra', durationMs: 800, speakerNote: 'Sự phân hóa diễn ra ngay trong lòng mỗi giai tầng về ngành nghề và mức độ thụ hưởng.' },
      { id: 'p1-s5-b2', label: 'Xuất hiện các tầng lớp xã hội mới mang tính minh họa', durationMs: 800, speakerNote: 'Kinh tế nhiều thành phần làm nảy sinh các tầng lớp mới như doanh nhân, tiểu chủ, lao động tự do.' },
      { id: 'p1-s5-b3', label: 'Các mối quan hệ và tương tác xã hội nhân rộng', durationMs: 800, speakerNote: 'Mối quan hệ kinh tế - xã hội đan xen, tạo thành mạng lưới tương tác đa chiều.' },
      { id: 'p1-s5-b4', label: 'Toàn cảnh diện mạo xã hội gia tăng độ phức tạp cấu trúc', durationMs: 900, speakerNote: 'Cơ cấu xã hội - giai cấp trở nên đa dạng, phong phú, phản ánh đúng tính chất TKQĐ.' },
    ],
    speakerNotes: [
      'Xu hướng 2: Sự tồn tại của nhiều thành phần kinh tế tất yếu dẫn đến sự phân hóa và xuất hiện các tầng lớp mới.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.2',
  },
  {
    id: 'p1-s6',
    chapterId: 'part-1',
    order: 6,
    kicker: '6. Sự biến đổi có tính quy luật — Xu hướng 3',
    title: 'Vừa đấu tranh vừa liên minh, từng bước xích lại gần nhau',
    subtitle: 'Hội tụ quanh lợi ích chung xây dựng chủ nghĩa xã hội',
    body: [
      'Cơ cấu xã hội – giai cấp biến đổi trong mối quan hệ vừa đấu tranh, vừa liên minh, từng bước dẫn đến sự xích lại gần nhau giữa các giai cấp, tầng lớp cơ bản trong xã hội.',
    ],
    visual: {
      id: 'convergence',
    },
    visualLabels: [
      { id: 'CLUSTER_A', text: 'Giai tầng A', sub: 'Lợi ích riêng & Khác biệt kinh tế' },
      { id: 'CLUSTER_B', text: 'Giai tầng B', sub: 'Lợi ích riêng & Khác biệt kinh tế' },
      { id: 'CLUSTER_C', text: 'Giai tầng C', sub: 'Lợi ích riêng & Khác biệt kinh tế' },
      { id: 'CLUSTER_D', text: 'Giai tầng D', sub: 'Lợi ích riêng & Khác biệt kinh tế' },
      { id: 'SHARED_FIELD', text: 'Trường lợi ích chung', sub: 'Mục tiêu xây dựng CNXH', role: 'Nền tảng khách quan quy tụ khối đại đoàn kết toàn dân' },
    ],
    beats: [
      { id: 'p1-s6-b0', label: 'Các cụm giai tầng tách biệt với vectơ lợi ích riêng', durationMs: 700, speakerNote: 'Các giai tầng ban đầu có sự khác biệt về địa vị kinh tế và lợi ích riêng.' },
      { id: 'p1-s6-b1', label: 'Khác biệt và căng thẳng lợi ích biểu hiện rõ', durationMs: 800, speakerNote: 'Mâu thuẫn và sự khác biệt về lợi ích dẫn tới nhu cầu đấu tranh khắc phục tiêu cực.' },
      { id: 'p1-s6-b2', label: 'Trường lực lợi ích chung xuất hiện', durationMs: 800, speakerNote: 'Trường lợi ích chung quốc gia và mục tiêu CNXH xuất hiện làm lực hút quy tụ.' },
      { id: 'p1-s6-b3', label: 'Các sợi dây liên kết, hợp tác liên minh hình thành', durationMs: 800, speakerNote: 'Các mối quan hệ hợp tác và liên minh kinh tế - chính trị được thiết lập vững chắc.' },
      { id: 'p1-s6-b4', label: 'Các cụm giai tầng từng bước dịch chuyển lại gần nhau', durationMs: 800, speakerNote: 'Khoảng cách giữa các giai tầng từng bước được thu hẹp trong quá trình phát triển.' },
      { id: 'p1-s6-b5', label: 'Vừa đấu tranh, vừa liên minh, từng bước xích lại gần nhau', durationMs: 900, speakerNote: 'Khắc sâu nguyên lý: Vừa đấu tranh, vừa liên minh, từng bước xích lại gần nhau.' },
    ],
    speakerNotes: [
      'Xu hướng 3: Đấu tranh để khắc phục tiêu cực, phân hóa bất bình đẳng; liên minh để phát huy sức mạnh tổng hợp xây dựng CNXH.',
    ],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I.2',
  },
  {
    id: 'p1-s7',
    chapterId: 'part-1',
    order: 7,
    kicker: '7. Chuyển tiếp sang Phần thứ hai',
    title: 'Cầu nối sang Liên minh giai cấp, tầng lớp',
    subtitle: 'Vì sao liên minh giai cấp, tầng lớp là đòi hỏi khách quan?',
    body: [
      'Nếu các giai cấp, tầng lớp vừa có lợi ích chung, vừa tồn tại những khác biệt về lợi ích, vì sao liên minh giữa họ trở thành một yêu cầu khách quan?',
    ],
    visual: {
      id: 'part1-bridge',
    },
    visualLabels: [
      { id: 'RECAP_CHAIN', text: 'Chuỗi quy luật cốt lõi', sub: 'Tổng kết Phần thứ nhất', role: 'Cơ cấu xã hội → Cơ cấu XH-GC → Cơ cấu kinh tế biến đổi → Cơ cấu XH-GC biến đổi → Lợi ích vừa thống nhất vừa khác biệt' },
      { id: 'CORE_QUESTION', text: 'Câu hỏi định hướng', sub: 'Đòi hỏi khách quan của Liên minh', role: 'Nếu vừa có lợi ích chung vừa có khác biệt, vì sao liên minh trở thành yêu cầu khách quan?' },
      { id: 'BOOK2_TEASE', text: 'QUYỂN II', sub: 'TÍNH TẤT YẾU CỦA LIÊN MINH', role: 'Cơ sở lý luận và thực tiễn của liên minh giai cấp, tầng lớp' },
    ],
    beats: [
      { id: 'p1-s7-b0', label: 'Recap: Chuỗi quy luật phát triển của Cơ cấu XH – Giai cấp', durationMs: 800, speakerNote: 'Hệ thống hóa toàn bộ chuỗi quy luật vận động của cơ cấu xã hội - giai cấp trong Phần I.' },
      { id: 'p1-s7-b1', label: 'Vấn đề cốt lõi: Đòi hỏi khách quan của Liên minh', durationMs: 900, speakerNote: 'Đặt câu hỏi bản lề: Vì sao liên minh giữa các giai tầng là một yêu cầu khách quan?' },
      { id: 'p1-s7-b2', label: 'Mạng lưới tri thức thu nhỏ về dạng trang sách', durationMs: 700, speakerNote: 'Mạng lưới kiến thức hội tụ lại chuẩn bị khép lại chương.' },
      { id: 'p1-s7-b3', label: 'Khép lại Phần thứ nhất', durationMs: 800, speakerNote: 'Hoàn tất nghiên cứu Phần thứ nhất: Khái luận về cơ cấu xã hội - giai cấp.' },
      { id: 'p1-s7-b4', label: 'Mở đường sang Quyển II: Tính tất yếu của Liên minh', durationMs: 900, speakerNote: 'Giới thiệu Quyển II: Liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH.' },
      { id: 'p1-s7-b5', label: 'Sẵn sàng chuyển giao', durationMs: 600, speakerNote: 'Sẵn sàng chuyển tiếp sang Thư viện hoặc Quyển II.' },
    ],
    speakerNotes: ['Đúc kết Phần I và mở đường dẫn dắt sang Quyển II: Liên minh giai cấp, tầng lớp trong thời kỳ quá độ lên CNXH.'],
    sourceNote: 'Giáo trình Chủ nghĩa xã hội khoa học, 2021, Chương 5, Mục I',
    transitionOut: 'book-close',
  },
];
